package com.demospace.approvereject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApproveData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("userid")
	private java.lang.String userId;
	@org.kie.api.definition.type.Label("userPhone")
	private java.lang.String userPhone;
	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;

	public ApproveData() {
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(java.lang.String userPhone) {
		this.userPhone = userPhone;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public ApproveData(java.lang.String userId, java.lang.String userPhone,
			java.lang.String status) {
		this.userId = userId;
		this.userPhone = userPhone;
		this.status = status;
	}

}